In [3]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
x = np.array([(1,2,3,4,5,6,7,8,9,10)])

y = np.array([(11,12,13,14,15,16,17,18,19,20)])

In [7]:
#Adding two arrays
print(x + y)
print (np.add(x,y))

[[12 14 16 18 20 22 24 26 28 30]]
[[12 14 16 18 20 22 24 26 28 30]]


In [9]:
#Subtracting two arrays
print(x - y)
print (np.subtract(x,y))

[[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]]
[[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]]


In [11]:
#Multiplying two arrays
print(x * y)
print (np.multiply(x,y))

[[ 11  24  39  56  75  96 119 144 171 200]]
[[ 11  24  39  56  75  96 119 144 171 200]]


In [12]:
#Dividinging two arrays
print(x / y)
print (np.divide(x,y))

[[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
  0.41176471 0.44444444 0.47368421 0.5       ]]
[[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
  0.41176471 0.44444444 0.47368421 0.5       ]]


In [13]:
import numpy as np

# Create 5 arrays
array1 = np.array([1, 4, 9, 16, 25])
array2 = np.array([2, 3, 5, 7, 11])
array3 = np.array([0, 0.5, 1, 1.5, 2])
array4 = np.array([10, 20, 30, 40, 50])
array5 = np.array([6, 8, 10, 12, 14])

# Store arrays in a list for easy iteration
arrays = [array1, array2, array3, array4, array5]

# Iterate through each array and calculate square root using a for loop
for idx, arr in enumerate(arrays):
    print(f"Square roots of elements in array{idx + 1}:")
    for num in arr:
        sqrt_num = np.sqrt(num)
        print(f"Square root of {num} is {sqrt_num}")
    print()  # Add a newline for readability


Square roots of elements in array1:
Square root of 1 is 1.0
Square root of 4 is 2.0
Square root of 9 is 3.0
Square root of 16 is 4.0
Square root of 25 is 5.0

Square roots of elements in array2:
Square root of 2 is 1.4142135623730951
Square root of 3 is 1.7320508075688772
Square root of 5 is 2.23606797749979
Square root of 7 is 2.6457513110645907
Square root of 11 is 3.3166247903554

Square roots of elements in array3:
Square root of 0.0 is 0.0
Square root of 0.5 is 0.7071067811865476
Square root of 1.0 is 1.0
Square root of 1.5 is 1.224744871391589
Square root of 2.0 is 1.4142135623730951

Square roots of elements in array4:
Square root of 10 is 3.1622776601683795
Square root of 20 is 4.47213595499958
Square root of 30 is 5.477225575051661
Square root of 40 is 6.324555320336759
Square root of 50 is 7.0710678118654755

Square roots of elements in array5:
Square root of 6 is 2.449489742783178
Square root of 8 is 2.8284271247461903
Square root of 10 is 3.1622776601683795
Square root of 1

In [16]:
import numpy as np

# Create an array
my_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Positive slicing
positive_slice1 = my_array[2:]  # Select elements from index 2 to the end (exclusive)
positive_slice2 = my_array[3:9]  # Select elements from index 3 to index 9 (exclusive)
positive_slice3 = my_array[:7]  # Select elements until index 6 (exclusive)

# Negative slicing
negative_slice1 = my_array[-8:]  # Select elements from 8th element from the end
negative_slice2 = my_array[-5:-2]  # Select elements from 5th element from the end to 2nd element from the end
negative_slice3 = my_array[:-4]  # Select elements until 4th element from the end

print("Original array:", my_array)
print("positive slice1:", positive_slice1)
print("positive slice2:", positive_slice2)
print("positive slice3:", positive_slice3)
print("Negative slice1:", negative_slice1)
print("Negative slice2:", negative_slice2)
print("Negative slice3:", negative_slice3)

Original array: [ 10  20  30  40  50  60  70  80  90 100]
positive slice1: [ 30  40  50  60  70  80  90 100]
positive slice2: [40 50 60 70 80 90]
positive slice3: [10 20 30 40 50 60 70]
Negative slice1: [ 30  40  50  60  70  80  90 100]
Negative slice2: [60 70 80]
Negative slice3: [10 20 30 40 50 60]


In [27]:
arr = np.array([[10, 20, 30, 40, 50, 60],[70, 80, 90, 100, 110, 120]])

print(arr[1, 2:6])
print(arr[1, 3:5])
print(arr[1, 1:4])


[ 90 100 110 120]
[100 110]
[ 80  90 100]


In [32]:
arr = np.array([[100, 200, 300, 400, 500, 600],[700, 800, 900, 1000, 1100, 1200]])
print(arr[0:1, 1])
print(arr[0:2, 2])
print(arr[0:3, 3])
print(arr[0:4, 4])
print(arr[0:5, 5])
print(arr[1:2, 2])
print(arr[1:3, 3])
print(arr[1:4, 4])
print(arr[1:5, 5])

[200]
[300 900]
[ 400 1000]
[ 500 1100]
[ 600 1200]
[900]
[1000]
[1100]
[1200]
