In [1]:
!pip install numpy

In [2]:
#import numpy
import numpy as np

In [3]:
# finding length of array

arr = np.array([[10,20,30,40,50],
                [11,21,31,41,51],
                [12,22,32,42,52],
                [13,23,33,43,53],
                [14,24,34,44,54]])
len(arr)

5

In [4]:
print(arr.shape)

(5, 5)


In [5]:
# accessing elements form array

arr = np.array([[10,20,30,40,50],
                [11,21,31,41,51],
                [12,22,32,42,52],
                [13,23,33,43,53],
                [14,24,34,44,54]])

print(arr[0,3]) #3rd element in row 1
print(arr[2,0]) #1st element in row 3
print(arr[3,4]) #5th element in row 4

40
12
53


In [6]:
# accessing 3D array

arr = np.array([[[11,52,55,94],[12,15,57,165]],  
                [[1,67,82,75],[46,22,748,92]],
                [[86,23,78,56],[89,22,43,47]],
                [[44,85,91,58],[81,32,31,72]]])

print(arr[3,0,2])

91


In [7]:
print(arr[1,1,3])

92


In [8]:
print(arr[2,0,2])

78


In [9]:
#reshaping elements

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120])
newarr= arr.reshape(12,10)
print(newarr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]]


In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120])

newarr = arr.reshape(5,4,6)
print(newarr)

[[[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]]

 [[ 25  26  27  28  29  30]
  [ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]]

 [[ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]
  [ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]]

 [[ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]
  [ 91  92  93  94  95  96]]

 [[ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]]


In [11]:
newarr = arr.reshape(3,2,20)
print(newarr)

[[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
    18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
    38  39  40]]

 [[ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
    58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
    78  79  80]]

 [[ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
    98  99 100]
  [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
   118 119 120]]]
